[tasks.build]
workspace = false
command = "cargo"
args = ["build"]

[tasks.build-mac-app]
workspace = false
dependencies = ["build"]
script = [
    """
    #!/usr/bin/env bash
    mkdir -p $CARGO_MAKE_CRATE_NAME.app/Contents/MacOS/
    cp target/debug/$CARGO_MAKE_CRATE_NAME $CARGO_MAKE_CRATE_NAME.app/Contents/MacOS/
    """
]

[tasks.run-mac-app]
workspace = false
dependencies = ["build-mac-app"]
script = [
    """
    #!/usr/bin/env bash
    open $CARGO_MAKE_CRATE_NAME.app
    """
]

[tasks.run-in-mac-app]
workspace = false
dependencies = ["build-mac-app"]
script = [
    """
    #!/usr/bin/env bash
    ./$CARGO_MAKE_CRATE_NAME.app/Contents/MacOS/$CARGO_MAKE_CRATE_NAME
    """
]

[tasks.build-wasm]
workspace = false
script = [
    """
    #!/usr/bin/env bash
    RUST_LOG=info cargo build --release --target wasm32-unknown-unknown --no-default-features --features="wasm_default"
    wasm-bindgen --no-typescript --out-name $CARGO_MAKE_CRATE_NAME --out-dir wasm --target web ${CARGO_TARGET_DIR:-target}/wasm32-unknown-unknown/release/$CARGO_MAKE_CRATE_NAME.wasm
    """
]

[tasks.watch-wasm]
workspace = false
watch = { watch = ["./src/", "./crates/"] }
script = [
    """
    #!/usr/bin/env bash
    RUST_LOG=info cargo build --release --target wasm32-unknown-unknown --no-default-features --features="wasm_default"
    wasm-bindgen --no-typescript --out-name $CARGO_MAKE_CRATE_NAME --out-dir wasm --target web ${CARGO_TARGET_DIR:-target}/wasm32-unknown-unknown/release/$CARGO_MAKE_CRATE_NAME.wasm
    """
]

[tasks.install-release]
description = "Installs cargo release."
category = "Test"
install_crate = { crate_name = "cargo-release", binary = "cargo-release", test_arg = "--help" }
args = [ "release", "--help" ]

[tasks.release]
workspace = false
dependencies = [ "install-release" ]
script = [
    """
    #!/usr/bin/env bash
    cargo release --package file://`pwd` ${@}
    """
]
